### ISSUE TITLE
Exception on initial opening of the settings dialog

### ISSUE THREAD

**Issue by StefanTT** [thred/climate-tray#27]
The cause is that the updatePeriodInMinutesSpinner in ClimateTrayPreferencesController works with integers, but model.getUpdatePeriodInMinutes() returns a double.

A cast fixes the problem for me:

```
public void refreshWith(ClimateTrayPreferences model)
{
    updatePeriodInMinutesSpinner.setValue((int) model.getUpdatePeriodInMinutes());
    .....
```

09:08:22.131 DEBUG: Opening preferences dialog.
Exception in thread "AWT-EventQueue-0" java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Integer
    at java.lang.Integer.compareTo(Integer.java:52)
    at javax.swing.SpinnerNumberModel.incrValue(SpinnerNumberModel.java:349)
    at javax.swing.SpinnerNumberModel.getPreviousValue(SpinnerNumberModel.java:388)
    at javax.swing.plaf.basic.BasicSpinnerUI.updateEnabledState(BasicSpinnerUI.java:501)
    at javax.swing.plaf.basic.BasicSpinnerUI.updateEnabledState(BasicSpinnerUI.java:481)
    at javax.swing.plaf.basic.BasicSpinnerUI.access$200(BasicSpinnerUI.java:50)
    at javax.swing.plaf.basic.BasicSpinnerUI$Handler.stateChanged(BasicSpinnerUI.java:1057)
    at javax.swing.JSpinner.fireStateChanged(JSpinner.java:458)
    at javax.swing.JSpinner$ModelListener.stateChanged(JSpinner.java:386)
    at javax.swing.AbstractSpinnerModel.fireStateChanged(AbstractSpinnerModel.java:119)
    at javax.swing.SpinnerNumberModel.setValue(SpinnerNumberModel.java:447)
    at javax.swing.JSpinner.setValue(JSpinner.java:354)
    at io.github.thred.climatetray.ui.ClimateTrayPreferencesController.refreshWith(ClimateTrayPreferencesController.java:82)
    at io.github.thred.climatetray.ui.ClimateTrayPreferencesController.refreshWith(ClimateTrayPreferencesController.java:33)
    at io.github.thred.climatetray.ui.AbstractClimateTrayWindowController.refreshWith(AbstractClimateTrayWindowController.java:191)
    at io.github.thred.climatetray.ui.AbstractClimateTrayController.prepareWith(AbstractClimateTrayController.java:62)
    at io.github.thred.climatetray.ui.AbstractClimateTrayWindowController.consume(AbstractClimateTrayWindowController.java:244)
    at io.github.thred.climatetray.ClimateTrayService.lambda$preferences$17(ClimateTrayService.java:349)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    ....

**Comment by thred** [comment]
Changed to seconds and to int value.
