### ISSUE TITLE
Unhandled ConcurrentModificationException

### ISSUE THREAD

**Issue by thred** [thred/climate-tray#6]
Unhandled error while update
Because of java.util.ConcurrentModificationException
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
    at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
    at io.github.thred.climatetray.ClimateTrayService.updateDevices(ClimateTrayService.java:135)
    at io.github.thred.climatetray.ClimateTrayService.update(ClimateTrayService.java:123)
    at io.github.thred.climatetray.ClimateTrayService.lambda$scheduleUpdate$40(ClimateTrayService.java:110)
    at io.github.thred.climatetray.ClimateTrayService$$Lambda$41/1061804750.run(Unknown Source)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

**Comment by thred** [comment]
'''
07:36:27.920 Opening popup.
07:36:29.714 Opening preferences dialog.
07:36:33.913 Closing proxy dialog.
07:36:35.280 Closing preferences dialog.
07:36:35.293 Preferences stored.
07:36:35.294 Canceling existing update process.
07:36:35.294 Scheduling update every 1,0 minutes.
07:37:06.999 Failed to request info of air conditioner "Raum 2360".
Because of io.github.thred.climatetray.mnet.request.MNetRequestException: Request to "http://10.224.10.118/servlet/MIMEReceiveServlet" failed with error 503.
    at io.github.thred.climatetray.mnet.request.AbstractMNetRequest.execute(AbstractMNetRequest.java:130)
    at io.github.thred.climatetray.mnet.MNetService.updateDevice(MNetService.java:50)
    at io.github.thred.climatetray.ClimateTrayService.lambda$updateDevices$42(ClimateTrayService.java:136)
    at io.github.thred.climatetray.ClimateTrayService$$Lambda$43/614910534.accept(Unknown Source)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
    at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
    at io.github.thred.climatetray.ClimateTrayService.updateDevices(ClimateTrayService.java:135)
    at io.github.thred.climatetray.ClimateTrayService.update(ClimateTrayService.java:123)
    at io.github.thred.climatetray.ClimateTrayService.lambda$scheduleUpdate$40(ClimateTrayService.java:110)
    at io.github.thred.climatetray.ClimateTrayService$$Lambda$41/1061804750.run(Unknown Source)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

07:37:07.002 Disabling air conditioner "Raum 2360".
07:37:07.005 Preferences stored.
07:37:07.012 Sending request to "http://10.224.10.118/servlet/MIMEReceiveServlet". The request is:
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<Packet>
<Command>getRequest</Command>
<DatabaseManager>
<Mnet AirDirection="*" Drive="*" Ec="1" FanSpeed="*" Group="23" InletTemp="*" Mode="*" SetTemp="*"/>
</DatabaseManager>
</Packet>

07:37:07.148 Reading response from "http://10.224.10.118/servlet/MIMEReceiveServlet". The response is:
<?xml version="1.0" encoding="UTF-8"?>
<Packet>
  <Command>getResponse</Command>
  <DatabaseManager>
    <Mnet AirDirection="HORIZONTAL" Drive="OFF" Ec="1" FanSpeed="MID1" Group="23" InletTemp="26.8" Mode="FAN" SetTemp="23" />
  </DatabaseManager>
</Packet>
07:37:07.151 Unhandled error while update
Because of java.util.ConcurrentModificationException
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
    at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
    at io.github.thred.climatetray.ClimateTrayService.updateDevices(ClimateTrayService.java:135)
    at io.github.thred.climatetray.ClimateTrayService.update(ClimateTrayService.java:123)
    at io.github.thred.climatetray.ClimateTrayService.lambda$scheduleUpdate$40(ClimateTrayService.java:110)
    at io.github.thred.climatetray.ClimateTrayService$$Lambda$41/1061804750.run(Unknown Source)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

07:37:07.155 Updating.
'''

**Comment by thred** [comment]
Failed to reproduce
